# Generated by Django 5.1.2 on 2025-02-01 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='esewa_transaction_id',
        ),
    ]
