# Generated by Django 5.1.5 on 2025-02-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_badge_certificate_leaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
